# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Variables Ambiente pre-determinadas

on:
  workflow_dispatch:

jobs:
  show:
    runs-on: macos-latest
    
    steps:
    - name: Mostrar valores de variables de ambiente
      run:  echo $GITHUB_ACTION &&
            echo $GITHUB_EVENT_NAME &&
            echo $GITHUB_REPOSITORY &&
            echo $GITHUB_RUN_NUMBER &&
            echo $GITHUB_WORKFLOW &&
            echo $GITHUB_WORKSPACE &&
            echo $RUNNER_NAME && 
            echo $RUNNER-OS &&
            echo $RUNNER_ARCH
